// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PennyWyse.Data;

namespace PennyWyse.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190511223556_PennyWyseDB")]
    partial class PennyWyseDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("PennyWyse.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City");

                    b.Property<int?>("CreatorId");

                    b.Property<string>("Description");

                    b.Property<string>("EventType");

                    b.Property<bool>("FamilyEvent");

                    b.Property<string>("ImageURL");

                    b.Property<string>("InfoURL");

                    b.Property<bool>("LegalAge");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Price");

                    b.Property<DateTime>("StartDate");

                    b.Property<string>("State");

                    b.Property<int?>("UserEventId");

                    b.Property<int>("UserId");

                    b.Property<string>("UserId1");

                    b.HasKey("EventId");

                    b.HasIndex("UserEventId");

                    b.HasIndex("UserId1");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            City = "Nashville",
                            Description = "Run Rock 'n' Roll Nashville Marathon, Half Marathon, 5k, and KiDS ROCK | The Rock 'n' Roll Nashville ... Join us in celebrating 20 years running in Music City!",
                            EventType = "Sports",
                            FamilyEvent = true,
                            ImageURL = "https://pridepublishinggroup.com/pride/wp-content/uploads/2019/01/st-jude-race.jpg",
                            InfoURL = "https://www.runrocknroll.com/nashville/",
                            LegalAge = false,
                            Name = "Music City Marathon",
                            Price = 50,
                            StartDate = new DateTime(2019, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = "Tennessee",
                            UserId = 0
                        },
                        new
                        {
                            EventId = 2,
                            City = "Nashville",
                            Description = "Bring the entire family and come enjoy Nashville's BEST Hot Air Balloon Festival! Is there any better way to kick off summer Tennessee ? !Held on a large field just minutes from downtown join dozens of vendors chefs local musicians artists cooking demonstrations pop - up art galleriesPLUS food and alcohol tasting partners.",
                            EventType = "Outdoor",
                            FamilyEvent = true,
                            ImageURL = "https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F52525323%2F211234311650%2F1%2Foriginal.jpg?w=800&auto=compress&rect=0%2C38%2C960%2C480&s=07e01664e96aca88dc46985863a58c81",
                            InfoURL = "https://victorycup.org/nashville/",
                            LegalAge = false,
                            Name = "Nashville Hot Air Balloon Festival",
                            Price = 300,
                            StartDate = new DateTime(2019, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = "Tennessee",
                            UserId = 0
                        },
                        new
                        {
                            EventId = 3,
                            City = "Nashville",
                            Description = "Don’t miss the second-annual Nashville Rosé Festival! One of the city’s most talked- and instagrammed-about events last year, we are thrilled celebrate our second year in East Nashville’s East Park and have another chance to support one of our favorite charities, the Tennessee Breast Cancer Coalition. ",
                            EventType = "Festival",
                            FamilyEvent = false,
                            ImageURL = "https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F50613290%2F33678832033%2F1%2Foriginal.jpg?w=800&auto=compress&rect=133%2C0%2C1654%2C827&s=6d96074a1714d0dc6514f98fe44049de",
                            InfoURL = "https://www.nashvillerosefestival.com/",
                            LegalAge = true,
                            Name = "Nashville Rosé Festival ",
                            Price = 40,
                            StartDate = new DateTime(2019, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = "Tennessee",
                            UserId = 0
                        },
                        new
                        {
                            EventId = 4,
                            City = "Nashville",
                            Description = "Nashville Zoo welcomes all species of beer lovers to the eighth annual Brew at the Zoo happening on Friday, May 31 from 6:30pm to 10:30pm. Animals, live music, local food trucks and over 100 craft beers are on tap at this unique after-hours event voted the best beer event in Nashville by Nashville Scene readers in 2014 and 2016.",
                            EventType = "Outdoor",
                            FamilyEvent = true,
                            ImageURL = "http://nashvilleguru.com/officialwebsite/wp-content/uploads/2015/05/Brew-at-the-Zoo.jpg",
                            InfoURL = "https://www.nashvillezoo.org/upcoming-events/entry/brew-at-the-zoo/instance/5-31-2019",
                            LegalAge = true,
                            Name = "Brew at the Zoo",
                            Price = 75,
                            StartDate = new DateTime(2019, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = "Tennessee",
                            UserId = 0
                        },
                        new
                        {
                            EventId = 5,
                            City = "Manchester",
                            Description = "The Bonnaroo Music and Arts Festival is an American annual four-day music festival developed and produced by Superfly Presents and AC Entertainment. Since its first year in 2002, it has been held at what is now Great Stage Park on a 650-acre (263 km2) farm in Manchester, Tennessee. The festival typically starts on the second Thursday in June and lasts four days. Main attractions of this festival are the multiple stages featuring live music with a diverse array of musical styles including indie rock, classic rock, world music, hip hop, jazz, americana, bluegrass, country music, folk, gospel, reggae, pop, electronic, and other alternative music.",
                            EventType = "Music Festival",
                            FamilyEvent = false,
                            ImageURL = "https://www.bonnaroo.com/wp-www-bonnaroo-com/wp/wp-content/uploads/2018/11/logo-1bb87d41-b09cb133.png",
                            InfoURL = "https://www.bonnaroo.com/",
                            LegalAge = true,
                            Name = "Bonnaroo",
                            Price = 350,
                            StartDate = new DateTime(2019, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = "Tennessee",
                            UserId = 0
                        },
                        new
                        {
                            EventId = 6,
                            City = "Nashville",
                            Description = "Pride parades are outdoor events celebrating lesbian, gay, bisexual, transgender, and queer social and self acceptance, achievements, legal rights and pride. The events also at times serve as demonstrations for legal rights such as same-sex marriage.",
                            EventType = "Parade",
                            FamilyEvent = true,
                            ImageURL = "http://nashvilleguru.com/officialwebsite/wp-content/uploads/2015/06/Nashville-Pride-Festival-1.jpg",
                            InfoURL = "https://www.nashvillepride.org/",
                            LegalAge = false,
                            Name = "Nashville Pride",
                            Price = 5,
                            StartDate = new DateTime(2019, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = "Tennessee",
                            UserId = 0
                        },
                        new
                        {
                            EventId = 7,
                            City = "Nashville",
                            Description = "WestEnd Kitchen & Bar is excited to welcome fans of celebrity magician Justin Flom with a special, An Evening of Magic dinner package. The package includes one entrée, one glass of house wine or beer, valet parking plus two general admission tickets to the show.",
                            EventType = "Show",
                            FamilyEvent = false,
                            ImageURL = "https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F56447862%2F50800243798%2F1%2Foriginal.20190207-205651?w=800&auto=compress&rect=0%2C0%2C2160%2C1080&s=a3bfbcc116e5622166604d60a6b2a5b5",
                            InfoURL = "https://www.eventbrite.com/e/an-evening-of-magic-with-justin-flom-at-analog-at-hutton-hotel-tickets-55677038521",
                            LegalAge = true,
                            Name = "An Evening of Magic with Justin Flom",
                            Price = 50,
                            StartDate = new DateTime(2019, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = "Tennessee",
                            UserId = 0
                        },
                        new
                        {
                            EventId = 8,
                            City = "Nashville",
                            Description = "The Master Gardeners of Davidson County will be hosting the Urban Gardening Festival on Saturday, May 18, 2019, from 9:00am to 4:00pm at the Ellington Agricultural Center. The public is invited to learn gardening methods, techniques, and engage with local growers, artisans, exhibitors, educators, and more. There will also be local food trucks with food and beverages. The event is rain or shine. All ages are welcome.",
                            EventType = "Outdoor Festival",
                            FamilyEvent = true,
                            ImageURL = "http://nashvilleguru.com/officialwebsite/wp-content/uploads/2018/05/Urban-Gardening-Fest-01.jpg",
                            InfoURL = "http://mgofdc.org/ugf",
                            LegalAge = false,
                            Name = "Urban Gardening Festival",
                            Price = 0,
                            StartDate = new DateTime(2019, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = "Tennessee",
                            UserId = 0
                        },
                        new
                        {
                            EventId = 9,
                            City = "Nashville",
                            Description = "The annual East Nashville Crawfish Bash is Saturday, May 25, 2019, from noon to 9:00pm in East Park. The East Nashville celebration will feature local food, art, music, and breweries for a family- and pet-friendly day of fun. Admission is free, but ticket options are also available if you want to secure a plate of crawfish or enjoy VIP perks.",
                            EventType = "Outdoor Festival",
                            FamilyEvent = true,
                            ImageURL = "https://pridepublishinggroup.com/pride/wp-content/uploads/2019/01/st-jude-race.jpg",
                            InfoURL = "http://eastnashcrawbash.com/",
                            LegalAge = false,
                            Name = "Nashville Crawfish Boil",
                            Price = 40,
                            StartDate = new DateTime(2019, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = "Tennessee",
                            UserId = 0
                        },
                        new
                        {
                            EventId = 10,
                            City = "Nashville",
                            Description = "Get ready country music fans—it’s almost time for Nashville’s most beloved music event, the CMA Music Festival. The event is Thursday through Sunday, June 6-9, 2019, in Downtown Nashville, and attracts about 80,000 locals and tourists for one weekend of country music lovin’.",
                            EventType = "Outdoor Festival",
                            FamilyEvent = true,
                            ImageURL = "https://cmafest.com/wp-content/uploads/2019/04/Ascend-Amphitheater-900x500-815x460.jpg",
                            InfoURL = "https://cmafest.com/",
                            LegalAge = true,
                            Name = "CMA Music Festival",
                            Price = 0,
                            StartDate = new DateTime(2019, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = "Tennessee",
                            UserId = 0
                        });
                });

            modelBuilder.Entity("PennyWyse.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("City");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("Family");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<bool>("LegalAge");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("ProfileImageURL");

                    b.Property<string>("SecurityStamp");

                    b.Property<string>("State");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "dcf34dc4-f990-45f7-9157-28359ab290cf",
                            AccessFailedCount = 0,
                            City = "Nashville",
                            ConcurrencyStamp = "56175bb5-d4c4-4a87-b603-49a908fd2595",
                            Email = "admin@admin.com",
                            EmailConfirmed = true,
                            Family = false,
                            FirstName = "admin",
                            LastName = "admin",
                            LegalAge = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ADMIN.COM",
                            NormalizedUserName = "ADMIN@ADMIN.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEJIuRYgvLdxsU9ms05nSrtvznaMSnGhJgK3Jyn0ee+jt5HQnbYnfvHlxIoY7VQWWuw==",
                            PhoneNumberConfirmed = false,
                            ProfileImageURL = "https://s3.amazonaws.com/37assets/svn/1065-IMG_2529.jpg",
                            SecurityStamp = "09f5240c-f512-4c4c-9b46-c55a8910fbf8",
                            State = "Tennessee",
                            TwoFactorEnabled = false,
                            UserName = "admin@admin.com"
                        },
                        new
                        {
                            Id = "c09c87f1-da8c-4ee3-941e-06bb56a6839c",
                            AccessFailedCount = 0,
                            City = "Nashville",
                            ConcurrencyStamp = "8770a899-0d82-4215-90ce-0ff449e6ca8d",
                            Email = "jd@jd.com",
                            EmailConfirmed = true,
                            Family = true,
                            FirstName = "JD",
                            LastName = "Wheeler",
                            LegalAge = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "JD@JD.COM",
                            NormalizedUserName = "JD@JD.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEIHgmoD1qGurkoK/lGlqCoL5khlEklsEoomArWWLqE0KSfUg+zEdpwKuSkC1exOPuA==",
                            PhoneNumberConfirmed = false,
                            ProfileImageURL = "https://s3.amazonaws.com/37assets/svn/1065-IMG_2529.jpg",
                            SecurityStamp = "71b2b062-c453-4b09-b962-7baa9d928221",
                            State = "Tennessee",
                            TwoFactorEnabled = false,
                            UserName = "jd@jd.com"
                        },
                        new
                        {
                            Id = "12a20ea7-cf1e-45b0-a1b5-449f446d68c2",
                            AccessFailedCount = 0,
                            City = "Nashville",
                            ConcurrencyStamp = "795fa7ad-efd3-40ad-9ebd-96de1ef931e6",
                            Email = "joey@joey.com",
                            EmailConfirmed = true,
                            Family = false,
                            FirstName = "Joey",
                            LastName = "B",
                            LegalAge = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "JOEY@JOEY.COM",
                            NormalizedUserName = "JOEY@JOEY.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEGk8s7QsG1vygSZxe3IR8XI+G3zYepCAE6QBJHrUdGgkEvmxGGTQIJG37PigCDvahw==",
                            PhoneNumberConfirmed = false,
                            ProfileImageURL = "https://s3.amazonaws.com/37assets/svn/1065-IMG_2529.jpg",
                            SecurityStamp = "690b52ab-378a-451a-8cd7-d1fa837cf42b",
                            State = "Tennessee",
                            TwoFactorEnabled = false,
                            UserName = "joey@joey.com"
                        });
                });

            modelBuilder.Entity("PennyWyse.Models.UserEvent", b =>
                {
                    b.Property<int>("UserEventId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EventId");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("UserEventId");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("UserEvents");

                    b.HasData(
                        new
                        {
                            UserEventId = 1,
                            EventId = 1,
                            UserId = "c09c87f1-da8c-4ee3-941e-06bb56a6839c"
                        },
                        new
                        {
                            UserEventId = 2,
                            EventId = 2,
                            UserId = "c09c87f1-da8c-4ee3-941e-06bb56a6839c"
                        },
                        new
                        {
                            UserEventId = 3,
                            EventId = 3,
                            UserId = "12a20ea7-cf1e-45b0-a1b5-449f446d68c2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PennyWyse.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PennyWyse.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PennyWyse.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PennyWyse.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PennyWyse.Models.Event", b =>
                {
                    b.HasOne("PennyWyse.Models.UserEvent")
                        .WithMany("Events")
                        .HasForeignKey("UserEventId");

                    b.HasOne("PennyWyse.Models.User", "User")
                        .WithMany("Events")
                        .HasForeignKey("UserId1");
                });

            modelBuilder.Entity("PennyWyse.Models.UserEvent", b =>
                {
                    b.HasOne("PennyWyse.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PennyWyse.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
